name: Cucumber Tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ecCucumber/eccucumber
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Run cucumber tests
        env:
          STANDARD_USERNAME: ${{ secrets.STANDARD_USERNAME}}
          STANDARD_PASSWORD: ${{ secrets.STANDARD_PASSWORD}}
        run: mvn test

      - name: Upload test report summary
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Cucumber Test Results
          path: "ecCucumber/eccucumber/target/surefire-reports/junitreports/*.xml"
          reporter: java-junit
          fail-on-error: false
